#!/bin/bash

# Color Definitions
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
RED='\033[0;31m'
green='\e[32m'
PURPLE='\e[35m'
cyan='\e[36m'
LRED='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
blue="\033[0;34m"
Blue="\033[36m"
clear

# System Information
domain=$(cat /etc/xray/domain)
WKT=$(curl -s ipinfo.io/timezone)
IPVPS=$(curl -s ipv4.icanhazip.com)
tram=$(free -m | awk 'NR==2 {print $2}')
swap=$(free -m | awk 'NR==4 {print $2}')
freq=$(awk -F: '/cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo)
cores=$(awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo)
cname=$(awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo)
knr=$(uname -r)

# Export IP Address
export IP=$(curl -s https://ipinfo.io/ip/)
clear

# Service Status
ssh_service=$( /etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1 )
openvpn_service=$( systemctl show openvpn.service --no-page | grep 'ActiveState=' | cut -f2 -d= )
dropbear_status=$( /etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1 )
haproxy_service=$( systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1 )
fail2ban_service=$( /etc/init.d/fail2ban status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1 )
cron_service=$( systemctl status cron | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1 )
badvpn1=$( systemctl status udp-mini-1 | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1 )
badvpn2=$( systemctl status udp-mini-2 | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1 )
badvpn3=$( systemctl status udp-mini-3 | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1 )
Iptables=$( systemctl status netfilter-persistent | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
RClocal=$( systemctl status rc-local | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
Autorebot=$( systemctl status rc-local | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
UdpSSH=$( systemctl status udp-custom | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
openssh=$( systemctl status ssh | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
clear

# Determine Statuses
status_openssh=$( [[ $openssh == "running" ]] && echo "ON" || echo "OFF" )
status_ws_epro=$( [[ $ssh_ws == "running" ]] && echo "ON" || echo "OFF" )
status_ss=$( [[ $ss == "running" ]] && echo "ON" || echo "OFF" )
status_nginx=$( [[ $nginx == "running" ]] && echo "ON" || echo "OFF" )
status_galo=$( [[ $Iptables == "exited" ]] && echo "ON" || echo "OFF" )
status_ssh=$( [[ $ssh_service == "running" ]] && echo "ON" || echo "OFF" )
status_noobz=$( [[ $noobz_service == "running" ]] && echo "ON" || echo "OFF" )
status_openvpn=$( [[ $oovpn == "active" ]] && echo "ON" || echo "OFF" )
status_beruangjatuh=$( [[ $dropbear_status == "running" ]] && echo "ON" || echo "OFF" )
status_haproxy=$( [[ $haproxy_service == "running" ]] && echo "ON" || echo "OFF" )
status_fail2ban=$( [[ $fail2ban_service == "running" ]] && echo "ON" || echo "OFF" )
status_cron=$( [[ $cron_service == "running" ]] && echo "ON" || echo "OFF" )
status_udp1=$( [[ $badvpn1 == "running" ]] && echo "ON" || echo "OFF" )
status_udp2=$( [[ $badvpn2 == "running" ]] && echo "ON" || echo "OFF" )
status_udp3=$( [[ $badvpn3 == "running" ]] && echo "ON" || echo "OFF" )
status_galoo=$( [[ $RClocal == "exited" ]] && echo "ON" || echo "OFF" )
status_galooo=$( [[ $Autorebot == "exited" ]] && echo "ON" || echo "OFF" )
status_udp=$( [[ $UdpSSH == "running" ]] && echo "ON" || echo "OFF" )

# Display Results
clear
echo
echo

printf "Service SSH / TUN                 %s\n" "$status_ssh"
printf "Service SSH UDP                   %s\n" "$status_udp"
printf "Service OpenVPN SSL               %s\n" "$status_openvpn"
printf "Service OpenVPN WS-SSL            %s\n" "$status_openvpn"
printf "Service OpenVPN UDP               %s\n" "$status_openvpn"
printf "Service OpenVPN TCP               %s\n" "$status_openvpn"
printf "Service OHP SSH                   %s\n" "$status_openvpn"
printf "Service OHP Dropbear              %s\n" "$status_openvpn"
printf "Service OHP OpenVPN               %s\n" "$status_openvpn"
printf "Service WS ePRO                   %s\n" "$status_ws_epro"
printf "Service BadVPN 7100               %s\n" "$status_udp1"
printf "Service BadVPN 7200               %s\n" "$status_udp2"
printf "Service BadVPN 7300               %s\n" "$status_udp3"
printf "Service IPTABLES                  %s\n" "$status_galo"
printf "Service RC LOCAL                  %s\n" "$status_galoo"
printf "Service AUTOREBOT                 %s\n" "$status_galooo"
printf "Service UDP CUSTOM                %s\n" "$status_udp"
