#!/bin/bash


#install
apt update && apt upgrade
apt install neofetch -y
apt install python3 python3-pip git
clear
neofetch
echo -e "  \e[92;1m Information System \e[0m"
echo -e "  \e[97;1m---------------------------------------"
echo -e "  \e[97;1m            ARISCTUNNEL V4             "
echo -e "  \e[97;1m---------------------------------------"
echo -e ""
