#!/bin/bash
# Fungsi untuk mengecek versi terbaru
cek_versi_baru() {
    # Mendapatkan versi terbaru dari URL update-cek
    versi_terbaru=$(curl -s https://raw.githubusercontent.com/xyzstoree/xyzv4/main/updatebot-cek)

     # Check if /usr/bin/menubot_version exists, if not create with version 1
  if [ ! -f /usr/bin/menubot_version ]; then
    echo "1" > /usr/bin/menubot_version
    echo "Version not found. Creating with version 1."
  fi
    # Versi saat ini (bisa disesuaikan dengan cara memperoleh versi lokal)
    versi_saat_ini=$(cat /usr/bin/menubot_version)

    # Membandingkan versi terbaru dengan versi saat ini
    if [[ "$versi_terbaru" != "$versi_saat_ini" ]]; then
        echo "Versi baru tersedia: $versi_terbaru"
        return 0  # Ada versi baru
    else
        echo "Versi sudah up-to-date: $versi_saat_ini"
        return 1  # Tidak ada versi baru
    fi
}

# Fungsi untuk menjalankan update jika ada versi terbaru
jalankan_update() {
    if cek_versi_baru; then
        echo "Menjalankan update ke versi terbaru..."
        sleep 3
        fun_bar res1  # Menjalankan fungsi update jika versi baru terdeteksi
    else
        echo "Tidak ada update yang diperlukan."
    fi
}

# Fungsi progress bar
fun_bar() {
    CMD[0]="$1"
    (
        ${CMD[0]} -y >/dev/null 2>&1
        touch /tmp/selesai_update
    ) &
    tput civis
    echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[0;32m#"
            sleep 0.1s
        done
        [[ -e /tmp/selesai_update ]] && rm /tmp/selesai_update && break
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "  Please Wait Loading \033[1;37m- \033[0;33m["
    done
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}

# Fungsi untuk download dan ekstraksi file update
res1() {
bash /usr/bin/install-bot.sh >/dev/null 2>&1
echo "$versi_terbaru" > /usr/bin/menubot_version  # Update versi lokal
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>◇━━━━━━━━━━━━━━◇</code>
<b>  ⚠️AUTOUPDATE2 NOTIF⚠️</b>
<code>◇━━━━━━━━━━━━━━◇</code>
<code>Auto Update Script Done</code>
<code>Versi : $versi_terbaru</code>
<code>◇━━━━━━━━━━━━━━◇</code>
"'&reply_markup={"inline_keyboard":[[{"text":"ᴏʀᴅᴇʀ","url":"https://wa.me/ARI_VPN_STORE"},{"text":"Contact","url":"https://wa.me/6281327393959"}]]}'

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

# Cek dan jalankan update jika ada
jalankan_update