#!/bin/bash
# Menu For Script
# Edition : Stable Edition V1.0
# =========================================
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[5;36'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White
UWhite='\033[4;37m'       # White
On_IPurple='\033[0;105m'  #
On_IRed='\033[0;101m'
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White
NC='\e[0m'

# // Export Color & Information
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LIGHT='\033[0;37m'
export NC='\033[0m'

# // Export Banner Status Information
export EROR="[${RED} EROR ${NC}]"
export INFO="[${YELLOW} INFO ${NC}]"
export OKEY="[${GREEN} OKEY ${NC}]"
export PENDING="[${YELLOW} PENDING ${NC}]"
export SEND="[${YELLOW} SEND ${NC}]"
export RECEIVE="[${YELLOW} RECEIVE ${NC}]"
clear
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
MYIP=$(wget -qO- icanhazip.com);
echo "Checking VPS"
clear
if [ ! -e /usr/local/bin/reboot_otomatis ]; then
cat <<EOF > /usr/local/bin/reboot_otomatis
#!/bin/bash
tanggal=\$(date +"%m-%d-%Y")
waktu=\$(date +"%T")
echo "Successfully Reboot On \$tanggal Time \$waktu." >> /root/log-reboot.txt
/sbin/shutdown -r now
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>◇━━━━━━━━━━━━━━◇</code>
<b>  AUTOREBOOT NOTIF⚠️</b>
<code>◇━━━━━━━━━━━━━━◇</code>
<code>Auto Reboot Server Done</code>
<code>◇━━━━━━━━━━━━━━◇</code>
"'&reply_markup={"inline_keyboard":[[{"text":"ᴏʀᴅᴇʀ","url":"https://wa.me/ARI_VPN_STORE"},{"text":"Contact","url":"https://wa.me/6281327393959"}]]}'

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
EOF
chmod +x /usr/local/bin/reboot_otomatis
    fi
clear
echo -e ""
echo -e "\033[5;36┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[5;36│$NC\033[42m           MENU MANAGER AUTOREBOOT        $NC"
echo -e "\033[5;36└──────────────────────────────────────────┘\033[0m"
echo -e "\033[5;36┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[5;36│  ${green}1.${NC} \033[0;36mSet Auto-Reboot Jam 1 Pagi"
echo -e "\033[5;36│  ${green}2.${NC} \033[0;36mSet Auto-Reboot Jam 2 Pagi"
echo -e "\033[5;36│  ${green}3.${NC} \033[0;36mSet Auto-Reboot Jam 3 Pagi"
echo -e "\033[5;36│  ${green}4.${NC} \033[0;36mSet Auto-Reboot Jam 4 Pagi"
echo -e "\033[5;36│  ${green}5.${NC} \033[0;36mSet Auto-Reboot Jam 5 Pagi"
echo -e "\033[5;36│  ${green}6.${NC} \033[0;36mSet Auto-Reboot Jam 6 Pagi"
echo -e "\033[5;36│  ${green}7.${NC} \033[0;36mSet Auto-Reboot Jam 7 Pagi"
echo -e "\033[5;36│  ${green}8.${NC} \033[0;36mSet Auto-Reboot Jam 8 Pagi"
echo -e "\033[5;36│  ${green}9.${NC} \033[0;36mSet Auto-Reboot Jam 9 Pagi"
echo -e "\033[5;36│  ${green}10.${NC} \033[0;36mSet Auto-Reboot Jam 10 Pagi"
echo -e "\033[5;36│  ${green}11.${NC} \033[0;36mSet Auto-Reboot Jam 11 Pagi"
echo -e "\033[5;36│  ${green}12.${NC} \033[0;36mSet Auto-Reboot Jam 12 Siang"
echo -e "\033[5;36│  ${green}13.${NC} \033[0;36mSet Auto-Reboot Jam 1 Siang"
echo -e "\033[5;36│  ${green}14.${NC} \033[0;36mSet Auto-Reboot Jam 2 Siang"
echo -e "\033[5;36│  ${green}15.${NC} \033[0;36mSet Auto-Reboot Jam 3 Sore"
echo -e "\033[5;36│  ${green}16.${NC} \033[0;36mSet Auto-Reboot Jam 4 Sore"
echo -e "\033[5;36│  ${green}17.${NC} \033[0;36mSet Auto-Reboot Jam 5 Sore"
echo -e "\033[5;36│  ${green}18.${NC} \033[0;36mSet Auto-Reboot Jam 6 Sore"
echo -e "\033[5;36│  ${green}19.${NC} \033[0;36mSet Auto-Reboot Jam 7 Malam"
echo -e "\033[5;36│  ${green}20.${NC} \033[0;36mSet Auto-Reboot Jam 8 Malam"
echo -e "\033[5;36│  ${green}21.${NC} \033[0;36mSet Auto-Reboot Jam 9 Malam"
echo -e "\033[5;36│  ${green}22.${NC} \033[0;36mSet Auto-Reboot Jam 10 Malam"
echo -e "\033[5;36│  ${green}23.${NC} \033[0;36mSet Auto-Reboot Jam 11 Malam"
echo -e "\033[5;36│  ${green}24.${NC} \033[0;36mSet Auto-Reboot Jam 12 Malam"
echo -e "\033[5;36│  $NC "
echo -e "\033[5;36│  ${green}0.${NC} \033[0;36mBACK TO EXIT MENU \033[1;32m<\033[1;33m<\033[1;31m<\033[1;31m$NC \E[0m\033[0;34m "
echo -e "\033[5;36└──────────────────────────────────────────┘\033[0m"
echo
read -p " Select menu : " opt
echo -e ""
case $opt in
1 | 01)
clear
echo "0 1 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 1 Pagi\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
2 | 02)
clear
echo "0 2 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 2 Pagi\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
3 | 03)
clear
echo "0 3 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 3 Pagi\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
4 | 04)
clear
echo "0 4 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 4 Pagi\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
5 | 05)
clear
echo "0 5 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 5 Pagi\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
6 | 06)
clear
echo "0 6 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 6 Pagi\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
7 | 07)
clear
echo "0 7 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 7 Pagi\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
8 | 08)
clear
echo "0 8 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 8 Pagi\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
9 | 09)
clear
echo "0 9 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 9 Pagi\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
10 | 10)
clear
echo "0 10 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 10 Pagi\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
11 | 11)
clear
echo "0 11 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 11 Pagi\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
12 | 12)
clear
echo "0 12 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 12 Siang\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
13 | 13)
clear
echo "0 13 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 1 Siang\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
14 | 14)
clear
echo "0 14 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 2 Siang\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
15 | 15)
clear
echo "0 15 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 3 Sore\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
16 | 16)
clear
echo "0 16 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 4 Sore\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
17 | 17)
clear
echo "0 17 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 5 Sore\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
18 | 18)
clear
echo "0 18 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 6 Sore\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
19 | 19)
clear
echo "0 19 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 7 Malam\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
20 | 20)
clear
echo "0 20 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 8 Malam\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
21 | 21)
clear
echo "0 21 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 9 Malam\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
22 | 22)
clear
echo "0 22 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 10 Malam\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
23 | 23)
clear
echo "0 23 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 11 Malam\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
24 | 24)
clear
echo "0 0 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
echo -e "Auto-Reboot Sucsesfully Set at \e[32mJam 12 Malam\e[0m"
echo -e "\033[5;36======================================\033[0m"
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
0 | 00)
clear
menu
;;
x)
exit
;;
*)
echo -e ""
menu
;;
esac
