#!/bin/bash
wget -O /usr/bin/ws "https://raw.githubusercontent.com/xyzstoree/xyzv4/main/Fls/ws" >/dev/null 2>&1
wget -O /usr/bin/tun.conf "https://raw.githubusercontent.com/xyzstoree/xyzv4/main/Cfg/tun.conf" >/dev/null 2>&1 
wget -O /etc/systemd/system/ws.service "https://raw.githubusercontent.com/xyzstoree/xyzv4/main/Fls/ws.service" >/dev/null 2>&1
chmod +x /etc/systemd/system/ws.service 
chmod +x /usr/bin/ws 
chmod 644 /usr/bin/tun.conf
systemctl disable ws 
systemctl stop ws 
systemctl enable ws 
systemctl start ws 
systemctl restart ws
