#!/bin/bash

yellow="\033[0;33m"
ungu="\033[0;35m"
Red="\033[91;1m"
Xark="\033[0m"
BlueCyan="\033[5;36m"
WhiteBe="\033[5;37m"
GreenBe="\033[5;32m"
YellowBe="\033[5;33m"
BlueBe="\033[5;34m"
Cyan="\033[96;1m"
KUNING="\033[93;1m"

# . Liner 
function baris_panjang() {
   echo -e "\033[5;36m ———————————————————————————————————————————————\033[0m"
}

function ARI_Banner() {
baris_panjang
echo -e "${ungu}            $nama      ${Xark} "
baris_panjang
}

function Sc_Credit(){
sleep 1
baris_panjang
function center_text() {
    local text="$1"
    local width=50  # Sesuaikan dengan panjang baris yang diinginkan

    # Hapus kode warna untuk menghitung panjang sebenarnya dari teks
    local plain_text=$(echo -e "$text" | sed 's/\x1b\[[0-9;]*m//g')
    local len=${#plain_text}
    local spaces=$(( (width - len) / 2 ))

    # Tampilkan teks dengan warna dan centering yang benar
    printf "%${spaces}s%s\033[0m\n" "" "$(echo -e "$text")"
}
# Kombinasi warna untuk ".::." dan "ARISCTUNNEL V4"
formatted_text="\033[0;35m Terimakasih sudah menggunakan- \033[0m"
formatted_text1="\033[0;35m Script Credit By $NAMASC \033[0m"
# Tampilkan teks yang diformat
center_text "$formatted_text"
center_text "$formatted_text1"
baris_panjang
read -n 1 -s -r -p " Press Enter for Back to Manage"
bash /usr/bin/m-tro
}

duration=6
frames=("██10%" "█████35%" "█████████65%" "█████████████80%" "█████████████████████90%" "█████████████████████████100%")

# Menghitung jumlah frame
num_frames=${#frames[@]}

# Menghitung jumlah iterasi
num_iterations=$((duration))

# Fungsi untuk menampilkan animasi loading berwarna

Loading_Animasi() {
    for ((i = 0; i < num_iterations; i++)); do
        clear
        index=$((i % num_frames))
        color_code=$((31 + i % 7))
echo ""
echo ""
echo ""
echo -e "\e[1;${color_code}m ${frames[$index]}\e[0m"
sleep 0.5
    done
}

# Menjalankan animasi loading
loading() {
  local pid=$1
  local delay=0.1
  local spin='-\|/'

  while ps -p $pid > /dev/null; do
    local temp=${spin#?}
    printf "[%c] " "$spin"
    local spin=$temp${spin%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done

  printf "    \b\b\b\b"
}

# Menampilkan pesan setelah animasi selesai
function Loading_Succes() {
clear
echo -e  "\033[5;32mSucces\033[0m"
sleep 1
clear
}


ARI_Banner
baris_panjang
    echo -e "${yellow}  Username   exp   ${Xark}" 
baris_panjang
echo ""	
	grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq
echo ""
baris_panjang
echo ""
read -p "Input Username :  " user
limit_file="/etc/kyt/limit/trojan/ip/${user}"

# Validasi apakah file batasan IP sudah ada
if [ -e "$limit_file" ]; then
  current_iplimit=$(cat "$limit_file")
baris_panjang
  echo -e "${Cyan} BEFORE ${Xark}"
  echo ""
  echo -e "${yellow} Username   : $user ${Xark} "
  echo -e "${yellow} Ip Limit   :  $current_iplimit ${Xark} "
baris_panjang
echo ""
echo ""
       read -p " Input New  Ip  :  " new_iplimit

  # Validasi jika masukan kosong
  if [ -z "$new_iplimit" ]; then


ARI_Banner
baris_panjang
    echo ""
    echo -e "${Red} Sorry ${Xarrk} "
    echo -e ""
    echo -e " Batasan ip Tidak di Temukan "
    echo -e " untuk Username : ${Green}$user ${Xark}"
    echo ""
    baris_panjang
    Sc_Credit
    
    
  else
echo "$new_iplimit" > "$limit_file"
ARI_Banner
    echo -e "${GreenBe} Succesfully ${Xark} "
echo ""
    echo -e "${KUNING} New Ip     : $new_iplimit ${Xark} "
    echo -e "${KUNING} Username   : $user ${Xark} "
echo ""
baris_panjang
Sc_Credit


  fi
else
ARI_Banner
baris_panjag
echo ""
  echo -e "${Cyan} File IP tidak ditemukan untuk : $user ${Xark} "
echo ""
baris_panjang
Sc_Credit
fi
