#!/bin/bash

BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[0;35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
BLUE="\033[4;34m"
BG_BLU="\033[44;1m" # BG BIRU
Xark='\e[0m'
GREN="\033[92m"
clear

function baris_panjang() {
  echo -e "${BlueCyan} ———————————————————————————————————————${Xark}"
}
function ATAS() {
  echo -e     "${ungu}         SSH-Dropbear-OpenVPN           ${Xark} "
}
function  MEMBER() {
  echo -e  " ${BG_BLU}                MEMBER                 ${Xark}"
}
function  LOCK_UNLOCK() {
  echo -e  " ${BG_BLU}             LOCK & UNLOCK             ${Xark}"
}
function  LIMIT() {
  echo -e  " ${BG_BLU}                 LIMIT                 ${Xark}"
}
function  OTHER() {
  echo -e  " ${BG_BLU}                 OTHER                 ${Xark}"
}

# . Create Ssh
function Create_Ssh() {
  bash /usr/bin/add-ssh
}

# . Create Triall
function Create_Trial() {
  bash /usr/bin/trial-ssh
}

# . Hapus akun ssh
function Delete_Ssh(){
  bash /usr/bin/del-ssh
}

# . List Member ssh
function List_Member() {
  bash /usr/bin/member-ssh
}

# . Auto Kill ssh
function Auto_Kill() {
  bash /usr/bin/auto-kill
}

# . Check user Login
function Check_Mullog() {
  bash /usr/bin/limitssh-ip
}

# . Delete Expiry
function Delete_Exp() {
  bash /usr/bin/delexp
}

# . Changes Limit
function Changes_Limit() {
  bash /usr/bin/Lt-on-off
}

# . Limit On off
function Limit_On_Off() {
  bash /usr/bin/Lt-on-off
}

#. Renew Ssh
function Renew_Ssh() {
  bash /usr/bin/renew-ssh
}

# . Lock Ssh
function Lock() {
  bash /usr/bin/lock
}

# . Unlock Ssh
function Unlock() {
  bash /usr/bin/unlock
}

# . Detail Akun Ssh
function Details_Account(){
  bash /usr/bin/user-ssh
}

function Monitor_Ssh() {
  bash /usr/bin/ceklim
}

function Recovery_Ssh() {
  bash /usr/bin/recover
}

# . Banner Ssh
function Banner() {
  baris_panjang
  ATAS
  baris_panjang
}
function Menu_Features() {
  baris_panjang
  echo -e ""
  echo -e "\033[0;37m  1.)  Check Users Login"
  echo -e "  2.)  Create Accounts"
  echo -e "  3.)  Delete Accounts"
  echo -e "  4.)  Renew Accounts"
  echo -e "  5.)  Trial Accounts"
  baris_panjang
  MEMBER
  baris_panjang
  echo -e "\033[0;37m  6.)  List Member Accounts"
  echo -e "  7.)  List Expired Accounts"
  baris_panjang
  LOCK_UNLOCK
  baris_panjang
  echo -e "\033[0;37m  8.)  Lock Accounts"
  echo -e "  9.)  Unlock Accounts"
  baris_panjang
  LIMIT
  baris_panjang
  echo -e "\033[0;37m 10.) Edit Limit IP Account"
  echo -e " 11.) Limit IP On Off Accounts"
  baris_panjang
  OTHER
  baris_panjang
  echo -e "\033[0;37m 12.) Auto Kill Accounts "
  echo -e " 13.) Detail Accounts"
  echo -e " 14.) Recovery Accounts"
  echo -e " 15.) Check Login UDP"
  baris_panjang
  echo -e "\033[0;37m 16.) Back to Menu"
  echo -e "  x.)  Exit"
  echo -e " "
  baris_panjang
  baris_panjang
}

Banner
Menu_Features
read -p "Select From Options [1-15 or x] :  " Ltt
case $Ltt in
1) clear ; Monitor_Ssh ;;
2) clear ; Create_Ssh ;;
3) clear ; Delete_Ssh ;;
4) clear ; Renew_Ssh ;;
5) clear ; Create_Trial ;;
6) clear ; List_Member ;;
7) clear ; Delete_Exp ;;
8) clear ; Lock ;;
9) clear ; Unlock ;;
10) clear ; bash /usr/bin/ganti-ip-ssh ;;
11) clear ; Limit_On_Off ;;
12) clear ; Check_Mullog ;;
13) clear ; Details_Account ;;
14) clear ; bash /usr/bin/recover ;;
15) clear ; bash /usr/bin/cekudp ;;
16) clear ; menu ;;
x) exit ;;
*) m-ssh ;;
esac
